# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

#trigger:
#- main
trigger:
  paths:
    include:
      - src/ApimAzureAdB2CSoln/Hello
      #- tools/code/extractor

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'APIM_MicrosoftAzureExternal_multitenant'

  # Function app name
  functionAppNameProd: 'fnappqnzxwgg2niqda'
  functionAppNameDev: 'fnapp3m2fbh7dapcag'

  # Agent VM image name
  vmImageName: 'windows-2019'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/ApimAzureAdB2CSoln/Hello'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy_Dev
  displayName: Deploy stage Dev
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'APIM_B2C_backend_development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            enabled: true # not ready to deploy yet!
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: $(functionAppNameDev)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
- stage: Deploy_Prod
  displayName: Deploy stage Prod
  dependsOn: Deploy_Dev
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'APIM_B2C_backend_production'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            enabled: true # not ready to deploy yet!
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: $(functionAppNameProd)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'