apimServiceName: apim-prod-006-xcilqlmt7zdw2
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "https://www.search2.com"
  - name: mysecretvalue
    properties:
      displayName: mysecretvalue
      value: "placeholder-update-with-prod-secret"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#testSecretValue#}"
  - name: weatherApiAudience
    properties:
      displayName: weatherApiAudience
      value: "7c0729e5-b6cf-4433-8742-0b3ff1d0bf56"
      tags:
        - prod_api
        - "PROD_audience"
  - name: developerPortalUrl
    properties:
      displayName: developerPortalUrl
      value: "https://apim-prod-006-xcilqlmt7zdw2.developer.azure-api.net"
      tags:
        - prod
        - developer
        - portal
  - name: sqlDatabaseConnectionString
    properties:
      displayName: sqlDatabaseConnectionString
      value: "placeholder-update-with-prod-connection-string"
      tags:
        - prod
        - sql
        - connection
        - string
apis:
  - name: echo-api
    properties:
      displayName: "Echo API"
      description: "PROD: Echo API"
      subscriptionRequired: false
      protocols:
        - https
  - name: demo-conference-api
    properties:
      displayName: "Demo Conference API"
      description: "PROD: Demo Conference API"
      subscriptionRequired: true
      protocols:
        - https
products:
  - name: starter
    properties:
      name: starter
      displayName: Starter (PROD)
      description: Starter product (PROD)
      approvalRequired: false
      state: "published"
      subscriptionRequired: true
      terms: "By using this product, you agree to the terms and conditions (PROD)"
  - name: unlimited
    properties:
      name: unlimited
      displayName: Unlimited (PROD)
      description: Unlimited product (PROD)
      approvalRequired: false
      state: "published"
      subscriptionRequired: true
      terms: "PROD: Read the legal fine print Unlimited-Terms!"
  - name: conference
    properties:
      name: conference
      displayName: Conference (PROD)
      description: Conference product (PROD)
      approvalRequired: false
      state: "published"
      subscriptionRequired: true
      terms: "PROD: Read the legal fine print Conference-Terms!"
  - name: graphql-product-dev
    properties:
      name: graphql-product-dev
      displayName: GraphQL Product (PROD)
      description: GraphQL product (PROD)
      approvalRequired: false
      state: "published"
      subscriptionRequired: true
      terms: "PROD: Read the legal fine print GraphQL-Terms!"
  - name: soapproduct
    properties:
      name: soapproduct
      displayName: SOAP Product (PROD)
      description: SOAP product (PROD)
      state: "published"
      subscriptionRequired: true
      terms: "PROD: Read the legal fine print SOAP-Terms!"
      subscriptionsLimit: 5
  - name: weatherproduct
    properties:
      name: weatherproduct
      displayName: Weather Product (PROD)
      description: Weather product (PROD)
      approvalRequired: false
      state: "published"
      subscriptionRequired: true
      terms: "PROD: Read the legal fine print Weather-Terms!"
  - name: odataproduct
    properties:
      name: odataproduct
      displayName: Odata Product (PROD)
      description: Odata product (PROD)
      approvalRequired: false
      state: "published"
      subscriptionRequired: true
      terms: "PROD: Read the legal fine print Odata-Terms!"
  - name: star-wars
    properties:
      name: star-wars
      displayName: Star Wars Product (PROD)
      description: Star Wars product (PROD)
      approvalRequired: false
      state: "published"
      subscriptionRequired: true
      terms: "PROD: Read the legal fine print Star-Wars-Terms!"
policyFragments:
  - name: SampleEmptyPolicyFragment
    properties:
      description: "Empty policy fragment (PROD)"
tags:
  - name: sampleapitag
    properties:
      displayName: sampleApiTagProd
  - name: WeatherForecast
    properties:
      displayName: WeatherForecastProd
