apimServiceName: apim-ekLZ11-prd-canadacentral-011
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "https://www.search2.com"
  - name: mysecretvalue
    properties:
      displayName: mysecretvalue
      value: some secret
      #keyVault:
      #  identityClientId: [identity client id goes here]
      #  secretIdentifier: [your url here]
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#testSecretValue#}"
  - name: helloworldfromfuncapp-key
    properties:
      displayName: helloworldfromfuncapp-key
      value: "{#helloworldfromfuncappkey#}"
  - name: 634e022983908257b35630b0
    properties:
      displayName: helloworldfromlogicapp_manual-invoke_634e022983908257b35630b0
      value: "{#helloworldfromlogicapp#}"  
loggers:
    - name: appi-ekLZ11-prd-canadacentral-011
      properties:
        loggerType: applicationInsights
        description: prod application insights
        resourceId: "/subscriptions/c04c476e-1725-4c9d-8a98-31f91163a0eb/resourceGroups/rg-apim-ekLZ11-prd-canadacentral-011/providers/microsoft.insights/components/appi-ekLZ11-prd-canadacentral-011"
        credentials:
          instrumentationKey: "{{Logger-Credentials--639918ba46346116dc7ad11d}}"
        isBuffered: true
diagnostics:
   - name: applicationinsights
     properties:
       verbosity: Error
       loggerId: "/subscriptions/c04c476e-1725-4c9d-8a98-31f91163a0eb/resourceGroups/rg-apim-ekLZ11-prd-canadacentral-011/providers/Microsoft.ApiManagement/service/apim-ekLZ11-prd-canadacentral-011/loggers/appi-ekLZ11-prd-canadacentral-011"
# backends:
#   - name: helloworldfromfuncapp
#     properties:
#       url: "https://helloworldfromprodfuncapp.azurewebsites.net/api"
#       resourceid: "https://management.azure.com/subscriptions/c04c476e-1725-4c9d-8a98-31f91163a0eb/resourceGroups/rg-apim-ApimLZ07-prd-canadacentral-007/providers/Microsoft.Web/sites/helloworldfromprodfuncapp"
#   - name: LogicApp_helloworldfromlogicapp_rg-apim-lab_77fadbdc74f14ce88962b34400a1f170
#     properties:
#       url: "https://prod-75.eastus.logic.azure.com/workflows/[guid goes here]/triggers"
#       resourceid: "https://management.azure.com/subscriptions/c04c476e-1725-4c9d-8a98-31f91163a0eb/resourceGroups/rg-apim-ApimLZ07-prd-canadacentral-007/providers/Microsoft.Logic/workflows/helloworldfromprodlogicapp"
apis:
  - name: demo-conference-api
    diagnostics:
      - name: applicationinsights
        properties:
          verbosity: Error
          loggerId: "/subscriptions/c04c476e-1725-4c9d-8a98-31f91163a0eb/resourceGroups/rg-apim-ekLZ11-prd-canadacentral-011/providers/Microsoft.ApiManagement/service/apim-ekLZ11-prd-canadacentral-011/loggers/appi-ekLZ11-prd-canadacentral-011"
subscriptions:
  - name: Dev-Sub
    properties:
      displayName: "Dev Subscription"
      allowTracing: false
      ownerId: "/subscriptions/c04c476e-1725-4c9d-8a98-31f91163a0eb/resourceGroups/rg-apim-ekLZ11-prd-canadacentral-011/providers/Microsoft.ApiManagement/service/apim-ekLZ11-prd-canadacentral-011/users/63991e9646346116dc7ad1b8"
      scope: /apis
      state: active