apis: [{weather: {diagnostics: [], releases: []}}, {software-version: {diagnostics: [], releases: []}}]
backends: [weather-backend, software-version-backend]
products: [demo]
namedValues: [demo-environment]
loggers: []
diagnostics: []
tags: []
policyFragments: []
gateways: []
versionSets: []
groups: []
subscriptions: []
schemas: []
policies: []
policyRestrictions: []
documentations: []
workspaces: []
