# Note: With the introduction of workspaces we recommend using workspaces with APIOps when possible to limit what can be extracted whenever possible. 
# More information about workspaces can be found here https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview

 apiNames:
  - apiName1_1
  - apiName1_2

 backendNames:
  - backendName1_1
  - backendName1_2

 diagnosticNames:
 - diagnosticName1_1
 - diagnosticName1_2

 loggerNames:
  - loggerName1_1
  - loggerName1_2

 namedValueNames:
  - namedValueName1_1
  - namedValueName1_2

 productNames:
  - productName1_1
  - productName1_2

 subscriptionNames:
 - subscriptionName1_1
 - subscriptionName1_2

 tagNames:
  - tagName1_1
  - tagName1_2
  
 policyFragmentNames:
  - policyFragment1_1
  - policyFragment1_2
