trigger:
  batch: true
  branches:
    include:
      - main
    exclude:
      - features/experimental/*
  paths:
    exclude:
      - README.md
    include:
      - src/msal-python-soln/python-flask-webapp/*
      # include pipeline file
      - .azuredevops/apps/deploy-flask-app.yml
      # include infra files
      - src/msal-python-soln/python-flask-webapp/main.bicep

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: "fe55e4ed-12be-41f8-87eb-5d661b8b8e83"

  # Web app name
  webAppName: "app-flask-iru5pc6fcyhre"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

  # Environment name
  environmentName: "APIM_app-flask-iru5pc6fcyhre"

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)/src/msal-python-soln/python-flask-webapp

  pythonVersion: "3.9"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
            displayName: "Use Python $(pythonVersion)"

          - script: |
              python -m venv antenv
              source antenv/bin/activate
              python -m pip install --upgrade pip
              pip install setup
              pip install -r requirements.txt
            workingDirectory: $(projectRoot)
            displayName: "Install requirements"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(projectRoot)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: "Upload package"
            artifact: drop

  - stage: Deploy
    displayName: "Deploy Web App"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          vmImage: $(vmImageName)
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: "$(pythonVersion)"
                  displayName: "Use Python version"

                - task: AzureWebApp@1
                  displayName: "Deploy Azure Web App : app-flask-iru5pc6fcyhre"
                  inputs:
                    azureSubscription: $(azureServiceConnectionId)
                    appName: $(webAppName)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
