# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
#   - none

trigger:
  batch: true
  branches:
    include:
      - main
    exclude:
      - features/experimental/*
  paths:
    exclude:
      - README.md
    include:
      - src/soap-service-dotnetcore-example/*
      - src/soap-service-dotnetcore-example/AddressBook.Service.SOAP/*
      - src/soap-service-dotnetcore-example/AddressBook.Service.SOAP/AddressBook.Service.SOAP.csproj
      - src/soap-service-dotnetcore-example/AddressBook.Service.SOAP/Dockerfile
      # include pipeline file
      - .azuredevops/apps/deploy-soap-api-v2.yml
      # include infra files
      - infra/webapp/main.bicep

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: deployInfra
    type: boolean
    default: true

variables:
  - name: solution
    value: "$(System.DefaultWorkingDirectory)/src/soap-service-dotnetcore-example/soap-service-dotnetcore-example.sln"
  - name: buildPlatform
    value: "Any CPU"
  - name: buildConfiguration
    value: "Release"
  - name: testProject
    value: "$(System.DefaultWorkingDirectory)/src/soap-service-dotnetcore-example/AddressBook.Service.SOAP.IntegrationTests/AddressBook.Service.SOAP.IntegrationTests.csproj"
  - name: artifactName
    value: "myWebsites"
  - name: azureSubscription
    value: APIM_MicrosoftAzureExternal_multitenant
  - name: websitePackageName
    value: AddressBook.Service.SOAP.zip
  - name: appName
    value: app-soap-api-l6isc4zatv5ny
  - name: resourceGroupName
    value: rg-soap-appservice-linux-002
  - name: location
    value: eastus2
  - name: deploymentName
    value: infra-deployment
  - name: templateFile
    value: $(System.DefaultWorkingDirectory)/infra/webapp/main.bicep
  - name: baseName
    value: soap-api

stages:
  - stage: set_version
    displayName: Set version and create tag
    jobs:
      - job: set_version
        displayName: Set version
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
          - task: gitversion/setup@3
            enabled: true
            displayName: "Install GitTools"
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@3
            enabled: true
            displayName: "Calculate SemVer"
          - script: echo current version is $(GitVersion.SemVer)
            displayName: "Display calculated version"
          - task: CmdLine@2
            enabled: true
            displayName: Init git global config
            inputs:
              script: |
                git config --global user.email $(Build.RequestedForEmail)
                git config --global user.name $(Build.RequestedFor)
          - task: CmdLine@2
            enabled: true
            displayName: Create Git tag for current version
            inputs:
              script: |
                git tag -a $(GitVersion.SemVer) -m "Main version $(GitVersion.SemVer)"
                git push origin $(GitVersion.SemVer)
  - stage: build
    displayName: Build
    dependsOn: set_version
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET Core SDK"
            inputs:
              version: 8.x
              performMultiLevelLookup: true
              includePreviewVersions: true # Required for preview versions
          - task: DotNetCoreCLI@2
            enabled: false
            displayName: "Restore NuGet packages"
            inputs:
              command: "restore"
              projects: "$(Solution)"
              feedsToUse: "config"
          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              projects: "$(Solution)"
              arguments: "--configuration $(buildConfiguration)"
            displayName: "dotnet build $(buildConfiguration)"
          - task: DotNetCoreCLI@2
            enabled: false
            inputs:
              command: test
              projects: $(testProject)
              arguments: "--configuration $(buildConfiguration)"
            displayName: "dotnet test $(buildConfiguration)"
          - script: dotnet test $(testProject) --logger trx
            enabled: false
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            enabled: false
            inputs:
              testRunner: VSTest
              testResultsFiles: "**/*.trx"
          - script: dotnet test $(testProject) --logger trx --collect "Code coverage"
            enabled: false
          - task: PublishTestResults@2
            enabled: false
            inputs:
              testRunner: VSTest
              testResultsFiles: "**/*.trx"
              mergeTestResults: true
          - task: DotNetCoreCLI@2
            inputs:
              command: "publish"
              publishWebProjects: true
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/soap-service-dotnetcore-example"
          # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifactName: $(artifactName)
  - stage: deployInfra
    displayName: Deploy Infra
    dependsOn: build
    condition: and(succeeded(), eq(variables['deployInfra'], true))
    jobs:
      - deployment: deploy
        displayName: Deploy
        environment: "APIM_Soap_Api_Infra_production"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # azure cli
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      echo "Deploying to Azure"
                      az group create --name $(resourceGroupName) \
                          --location $(location)

                      az deployment group create --name $(deploymentName) \
                          --resource-group $(resourceGroupName) \
                          --template-file $(templateFile) \
                          --parameters baseName=$(baseName)
  - stage: Deploy
    displayName: Deploy App
    dependsOn: deployInfra
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: "APIM_Soap_Api_production"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    appType: "webAppLinux"
                    appName: "$(appName)"
                    package: "$(Pipeline.Workspace)/$(artifactName)/$(websitePackageName)"
