# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - none

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  - name: dockerRegistryServiceConnection
    value: "f8c88b8a-490f-409d-8b47-c48f859e659a"
  - name: imageRepository
    value: "weatherapi"
  - name: containerRegistry
    value: "crweathapigyt73mi6rca7g.azurecr.io"
  - name: dockerfilePath
    value: "$(Build.SourcesDirectory)/src/WeatherApiSoln/WeatherApi/Dockerfile"
  - name: tag
    value: "$(Build.BuildId)"
  - name: buildContext
    value: "$(Build.SourcesDirectory)/src/WeatherApiSoln"
  - name: vmImageName
    value: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              repository: "$(imageRepository)"
              command: "buildAndPush"
              Dockerfile: "$(dockerfilePath)"
              buildContext: $(buildContext)
              tags: |
                $(tag)
                latest
