# trigger:
#   - none

trigger:
  batch: true
  branches:
    include:
      - main
    exclude:
      - features/experimental/*
  paths:
    exclude:
      - README.md
    include:
      - src/StarWarsApiNetSoln/StarWarsApiNet/*
      - src/StarWarsApiNetSoln/*
      - src/StarWarsApiNetSoln/StarWarsApiNet/Dockerfile
      # include pipeline file
      - .azuredevops/apps/deploy-star-wars-api.yml
      # include infra files
      - infra/appservice/main.bicep

pool:
  #vmImage: "ubuntu-latest"
  name: "DefaultLinuxOnPremPool"

parameters:
  - name: deployInfra
    type: boolean
    default: true
  - name: instanceNumber
    type: string
    default: 003

variables:
  - name: solution
    value: "$(System.DefaultWorkingDirectory)/src/StarWarsApiNetSoln/StarWarsApiNetSoln.sln"
  - name: buildPlatform
    value: "Any CPU"
  - name: buildConfiguration
    value: "Release"
  #- name: testProject
  #  value: "$(System.DefaultWorkingDirectory)/src/soap-service-dotnetcore-example/AddressBook.Service.SOAP.IntegrationTests/AddressBook.Service.SOAP.IntegrationTests.csproj"
  - name: artifactName
    value: "myWebsites"
  - name: azureSubscription
    value: APIM_MicrosoftAzureExternal_multitenant
  - name: websitePackageName
    value: StarWarsApi
  #- name: appName
  #  value: app-soap-api-l6isc4zatv5ny
  - name: resourceGroupName
    value: rg-star-wars-appservice-linux-${{ parameters.instanceNumber }}
  - name: location
    value: eastus2
  - name: deploymentName
    value: infra-deployment
  - name: templateFile
    value: $(System.DefaultWorkingDirectory)/infra/appservice/main.bicep
  - name: baseName
    value: star-wars-api
  - name: imageName
    value: starwarsapi
  - name: deployInfra
    value: ${{ parameters.deployInfra }}
  - name: workingDirectory
    value: "$(System.DefaultWorkingDirectory)/src/StarWarsApiNetSoln/StarWarsApiNet"
  - name: workingDirectoryDockerContext
    value: "$(System.DefaultWorkingDirectory)/src/StarWarsApiNetSoln"
  - name: dockerfilePath
    value: "$(System.DefaultWorkingDirectory)/src/StarWarsApiNetSoln/StarWarsApiNet/Dockerfile"
  - name: environmentNameInfra
    value: APIM_StarWars_Api_infra_production_${{ parameters.instanceNumber }}
  - name: environmentNameApp
    value: APIM_StarWars_Api_app_production_${{ parameters.instanceNumber }}

stages:
  - stage: set_version
    displayName: Set version and create tag
    jobs:
      - job: set_version
        displayName: Set version
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
          - task: gitversion/setup@3
            enabled: true
            displayName: "Install GitTools"
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@3
            enabled: true
            displayName: "Calculate SemVer"
          - script: echo current version is $(GitVersion.SemVer)
            displayName: "Display calculated version"
          - task: CmdLine@2
            enabled: true
            displayName: Init git global config
            inputs:
              script: |
                git config --global user.email $(Build.RequestedForEmail)
                git config --global user.name $(Build.RequestedFor)
          - task: CmdLine@2
            enabled: true
            displayName: Create Git tag for current version
            inputs:
              script: |
                git tag -a $(GitVersion.SemVer) -m "Main version $(GitVersion.SemVer)"
                git push origin $(GitVersion.SemVer)
  - stage: build
    displayName: Build
    dependsOn: set_version
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
          - task: gitversion/setup@3
            enabled: true
            displayName: "Install GitTools"
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@3
            enabled: true
            displayName: "Calculate SemVer"
          - script: echo current version is $(GitVersion.SemVer)
            displayName: "Display calculated version"
          - task: UseDotNet@2
            displayName: "Install .NET Core SDK"
            inputs:
              version: 8.x
              performMultiLevelLookup: true
              includePreviewVersions: true # Required for preview versions
          - task: DotNetCoreCLI@2
            enabled: false
            displayName: "Restore NuGet packages"
            inputs:
              command: "restore"
              projects: "$(Solution)"
              feedsToUse: "config"
          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              projects: "$(Solution)"
              arguments: "--configuration $(buildConfiguration)"
            displayName: "dotnet build $(buildConfiguration)"
          - task: DotNetCoreCLI@2
            enabled: false
            inputs:
              command: test
              projects: $(testProject)
              arguments: "--configuration $(buildConfiguration)"
            displayName: "dotnet test $(buildConfiguration)"
          - script: dotnet test $(testProject) --logger trx
            enabled: false
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            enabled: false
            inputs:
              testRunner: VSTest
              testResultsFiles: "**/*.trx"
          - script: dotnet test $(testProject) --logger trx --collect "Code coverage"
            enabled: false
          - task: PublishTestResults@2
            enabled: false
            inputs:
              testRunner: VSTest
              testResultsFiles: "**/*.trx"
              mergeTestResults: true
          - task: DotNetCoreCLI@2
            displayName: "Publish Artifact (dotnet publish)"
            inputs:
              command: "publish"
              publishWebProjects: false
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(websitePackageName)_$(Build.BuildId) -p:Version=$(GitVersion.SemVer) -p:FileVersion=$(GitVersion.AssemblySemFileVer) -p:AssemblyVersion=$(GitVersion.AssemblySemVer)"
              workingDirectory: "$(workingDirectory)"
          # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/$(websitePackageName)_$(Build.BuildId)"
              artifactName: $(artifactName)
  - stage: deployInfra
    displayName: Deploy Infra
    dependsOn: build
    condition: and(succeeded(), eq(variables['deployInfra'], true))
    jobs:
      - deployment: deploy
        displayName: Deploy Infra job
        environment: ${{ variables.environmentNameInfra }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # azure cli
                - task: AzureCLI@2
                  displayName: "Azure CLI Login $(azureSubscription) - deployInfra"
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      echo "Deploying to Azure"
                      az group create --name $(resourceGroupName) \
                          --location $(location)

                      az deployment group create --name $(deploymentName) \
                          --resource-group $(resourceGroupName) \
                          --template-file $(templateFile) \
                          --parameters baseName=$(baseName) \
                          --parameters imageName=$(imageName)
  - stage: BuildAndPush
    displayName: Build and push stage
    dependsOn: deployInfra
    jobs:
      - job: BuildImage
        displayName: Build and push an image to container registry
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
          - task: gitversion/setup@3
            enabled: true
            displayName: "Install GitTools"
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@3
            enabled: true
            displayName: "Calculate SemVer"
          - script: echo current version is $(GitVersion.SemVer)
            displayName: "Display calculated version"
          # get container registry from azure deployment with azure cli
          - task: AzureCLI@2
            displayName: "Azure CLI Login $(azureSubscription) - get_container_registry"
            name: get_container_registry
            inputs:
              azureSubscription: "$(azureSubscription)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                echo "Getting container registry"
                containerRegistryName=$(az deployment group show --name $(deploymentName) \
                  --resource-group $(resourceGroupName) \
                  --query properties.outputs.containerRegistryName.value \
                  -o tsv)
                echo "Container Registry: $containerRegistryName"
                echo "##vso[task.setvariable variable=containerRegistry;isOutput=true]$containerRegistryName"
              workingDirectory: "$(workingDirectory)"
          # echo container registry
          - script: echo $(get_container_registry.containerRegistry)
            displayName: "Container Registry"
          # build and push image to container registry via azure cli
          - task: AzureCLI@2
            displayName: "Azure CLI Login $(azureSubscription) - Build and push image"
            inputs:
              azureSubscription: "$(azureSubscription)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                echo "Building and pushing image to container registry"                
                az acr build --registry $(get_container_registry.containerRegistry) \
                  --image $(imageName):$(Build.BuildId) \
                  --image $(imageName):latest \
                  --file $(dockerfilePath) \
                  --build-arg GitVersion_SemVer=$(GitVersion.SemVer) \
                  --build-arg GitVersion_AssemblySemFileVer=$(GitVersion.AssemblySemFileVer) \
                  --build-arg GitVersion_AssemblySemVer=$(GitVersion.AssemblySemVer) \
                  $(workingDirectoryDockerContext)
  - stage: Deploy
    displayName: Deploy App
    dependsOn: BuildAndPush
    jobs:
      - deployment: Deploy
        displayName: Deploy App job
        environment: ${{ variables.environmentNameApp }}
        strategy:
          runOnce:
            deploy:
              steps:
                # get app name from azure deployment with azure cli
                - task: AzureCLI@2
                  displayName: "Azure CLI Login $(azureSubscription) - get_app_name"
                  name: get_app_name
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      echo "Getting app name"
                      appName=$(az deployment group show --name $(deploymentName) \
                        --resource-group $(resourceGroupName) \
                        --query properties.outputs.appName.value \
                        -o tsv)
                      echo "App Name: $appName"
                      echo "##vso[task.setvariable variable=appName;isOutput=true]$appName"
                # echo app name
                - script: echo $(get_app_name.appName)
                  displayName: "App Name"
                # extract website package in temp folder and show content recursively
                - task: ExtractFiles@1
                  displayName: "Extract $(artifactName)"
                  inputs:
                    archiveFilePatterns: "$(Pipeline.Workspace)/$(artifactName)/$(websitePackageName)_$(Build.BuildId).zip"
                    destinationFolder: "$(Pipeline.Workspace)/$(artifactName)/$(websitePackageName)_$(Build.BuildId)"
                - script: ls -R $(Pipeline.Workspace)/$(artifactName)/$(websitePackageName)_$(Build.BuildId)
                  displayName: "List files in $(Pipeline.Workspace)/$(artifactName)/$(websitePackageName)_$(Build.BuildId)"
                - task: AzureWebApp@1
                  displayName: "Azure Web App Deploy"
                  enabled: false
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    appType: "webAppLinux"
                    appName: "$(get_app_name.appName)"
                    package: "$(Pipeline.Workspace)/$(artifactName)/$(websitePackageName)_$(Build.BuildId).zip"
