trigger:
  batch: true
  branches:
    include:
      - main
    exclude:
      - features/experimental/*
  paths:
    exclude:
      - README.md
    include:
      - src/msal-python-soln/python-flask-webapp/*
      # include pipeline file
      - .azuredevops/apps/deploy-flask-app.yml
      # include infra files
      - src/msal-python-soln/python-flask-webapp/main.bicep

variables:
  # Azure Resource Manager connection created during pipeline creation
  - name: azureServiceConnectionId
    value: "fe55e4ed-12be-41f8-87eb-5d661b8b8e83"
  # Web app name
  - name: webAppName
    value: "app-flask-iru5pc6fcyhre"
  # Agent VM image name
  - name: vmImageName
    value: "ubuntu-latest"
  # Environment name
  - name: environmentName
    value: "APIM_app-flask-iru5pc6fcyhre"
  # Environment name for infra
  - name: environmentNameInfra
    value: "APIM_app-flask-iru5pc6fcyhre_Infra"
  # Project root folder. Point to the folder containing manage.py file.
  - name: projectRoot
    value: $(System.DefaultWorkingDirectory)/src/msal-python-soln/python-flask-webapp
  # Location of the main.bicep file
  - name: templateFile
    value: $(System.DefaultWorkingDirectory)/src/msal-python-soln/python-flask-webapp/main.bicep
  - name: pythonVersion
    value: "3.9"
  - name: ResourceGroupName
    value: "rg-msal-python-soln"
  - name: Location
    value: "canadacentral"
  - name: deploymentName
    value: "infra-deployment"
  - group: APIM_flask_app_vars
  - name: appConfigFile
    value: $(System.DefaultWorkingDirectory)/src/msal-python-soln/python-flask-webapp/app_config.py

stages:
  - stage: set_version
    displayName: Set version and create tag
    jobs:
      - job: set_version
        displayName: Set version
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
          - task: gitversion/setup@3
            enabled: true
            displayName: "Install GitTools"
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@3
            enabled: true
            displayName: "Calculate SemVer"
          - script: echo current version is $(GitVersion.SemVer)
            displayName: "Display calculated version"
          - task: CmdLine@2
            enabled: true
            displayName: Init git global config
            inputs:
              script: |
                git config --global user.email $(Build.RequestedForEmail)
                git config --global user.name $(Build.RequestedFor)
          - task: CmdLine@2
            enabled: true
            displayName: Create Git tag for current version
            inputs:
              script: |
                git tag -a $(GitVersion.SemVer) -m "Main version $(GitVersion.SemVer)"
                git push origin $(GitVersion.SemVer)
  - stage: Build
    displayName: Build stage
    dependsOn: set_version
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
            displayName: "Use Python $(pythonVersion)"

          - script: |
              python -m venv antenv
              source antenv/bin/activate
              python -m pip install --upgrade pip
              pip install setup
              pip install -r requirements.txt
            workingDirectory: $(projectRoot)
            displayName: "Install requirements"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(projectRoot)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: "Upload package"
            artifact: drop
  - stage: deployInfra
    displayName: "Deploy Infra"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          vmImage: $(vmImageName)
        environment: $(environmentNameInfra)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  persistCredentials: true
                  fetchDepth: 0
                - task: gitversion/setup@3
                  enabled: true
                  displayName: "Install GitTools"
                  inputs:
                    versionSpec: "5.x"
                - task: gitversion/execute@3
                  enabled: true
                  displayName: "Calculate SemVer"
                - script: echo current version is $(GitVersion.SemVer)
                  displayName: "Display calculated version"
                # run bash script to find and replace values in the app_config.py file
                - bash: |
                    # find and replace values in the app_config.py file
                    # replace the value of '__VERSION__' with the value of the variable $(GitVersion.SemVer)
                    echo "Replacing values in app_config.py file"
                    echo "Replacing __VERSION__ with $(GitVersion.SemVer)"                   
                    sed -i "s/__VERSION__/$(GitVersion.SemVer)/g" $(appConfigFile)
                  displayName: "Find and replace values in app_config.py file"
                - task: AzureCLI@2
                  displayName: "Deploy Infrastructure"
                  inputs:
                    azureSubscription: $(azureServiceConnectionId)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az group create --name $(ResourceGroupName) \
                          --location $(Location)

                      # deploy infrastructure
                      az deployment group create --resource-group $(ResourceGroupName) \
                          --name $(deploymentName) \
                          --template-file $(templateFile) \
                          --parameters secretValue=$(secretValue) \
                          --parameters pythonVersion=$(pythonVersion)
  - stage: DeployWebApp
    displayName: "Deploy Web App"
    dependsOn: DeployInfra
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          vmImage: $(vmImageName)
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: "$(pythonVersion)"
                  displayName: "Use Python version"

                - task: AzureWebApp@1
                  displayName: "Deploy Azure Web App : app-flask-iru5pc6fcyhre"
                  inputs:
                    azureSubscription: $(azureServiceConnectionId)
                    appName: $(webAppName)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
