openapi: 3.0.1
info:
  title: func-b2c-011
  description: so be happy linter
  version: '1.0'
servers:
  - url: https://apim-gk7dxthmtgpwg.azure-api.net/func-b2c-011
paths:
  /hello:
    get:
      summary: Hello
      description: for my linter friend
      operationId: get-hello
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]