# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- name: internalVnetName
  value: vnet-apim-cs-ApimESLZ-dev-canadacentral-002
- name: domainName
  value: MngEnv019702.onmicrosoft.com
- name: zoneName
  value: MngEnv019702.onmicrosoft.com
- name: ResourceGroupNameApim 
  value: rg-apim-ApimESLZ-dev-canadacentral-002
- name: apimServiceName
  value: apim-ApimESLZ-dev-canadacentral-002
- group: APIM_apim-landing-zone-accelerator_common
- name: appGatewayName
  value: appgw-ApimESLZ-dev-canadacentral-002
- name: Location
  value: canadacentral
- name: apimOrganization
  value: "Contoso MngEnv019702"
- name: apimAdminEmail
  value: "admin@MngEnv019702.onmicrosoft.com" # Administrator's email address
- group: APIM_apim-landing-zone-accelerator_common

stages :
- stage: get_and_set_version
  dependsOn: []
  jobs:
  - job: Set_tag_for_version
    displayName: set version once
    steps:
    - checkout: self
      persistCredentials: true
    - task: gitversion/setup@0
      enabled: true
      displayName: 'Install GitTools'
      inputs:
        versionSpec: '5.x'
    - task: gitversion/execute@0
      enabled: true
      displayName: 'Calculate SemVer'
    - script: echo current version is $(GitVersion.SemVer)
      displayName: 'Display calculated version'
    - task: CmdLine@2
      enabled: true
      displayName: Init git global config
      inputs:
        script: |
          git config --global user.email $(Build.RequestedForEmail)
          git config --global user.name $(Build.RequestedFor)
    - task: CmdLine@2
      enabled: true
      displayName: Create Git tag for current version
      inputs:
        script: |
          git tag -a $(GitVersion.SemVer) -m "Main version $(GitVersion.SemVer)"
          git push origin $(GitVersion.SemVer)       
- stage: appGateway
  dependsOn: get_and_set_version
  jobs:
  - job: appGatewayJob
    steps:
    - checkout: self
      persistCredentials: true
    - task: gitversion/setup@0
      enabled: true
      displayName: 'Install GitTools'
      inputs:
        versionSpec: '5.x'
    - task: gitversion/execute@0
      enabled: true
      displayName: 'Calculate SemVer'
    - script: echo current version is $(GitVersion.SemVer)
      displayName: 'Display calculated version'
    - task: DownloadSecureFile@1
      name: pfxApiTask
      inputs:
        secureFile: 'APIM_apim-landing-zone-accelerator_api.pfx'
    - task: DownloadSecureFile@1
      name: pfxManagementTask
      inputs:
        secureFile: 'APIM_apim-landing-zone-accelerator_management.pfx'
    - task: DownloadSecureFile@1
      name: pfxPortalTask
      inputs:
        secureFile: 'APIM_apim-landing-zone-accelerator_portal.pfx'
    - task: DownloadSecureFile@1
      name: trustedrootcert
      inputs:
        secureFile: 'APIM_apim-landing-zone-accelerator_cacert.pem'
    
    - task: AzureCLI@2
      enabled: false
      displayName: Do the Dew - Idempotent
      inputs:
        azureSubscription: 'APIM_MicrosoftAzureExternal_multitenant'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: '$(System.DefaultWorkingDirectory)/infra/scripts/main.ps1'
        arguments: '-Location $(Location) -ResourceGroupNameApim $(ResourceGroupNameApim) -zoneName $(zoneName) -appGatewayName $(appGatewayName) -GitVersionSemVer $(GitVersion.SemVer) -apimServiceName $(apimServiceName) -domainName $(domainName) -apimOrganization "$(apimOrganization)" -apimAdminEmail $(apimAdminEmail) -pfxPassword $(pfxPassword) -trustedrootcertsecureFIlePath $(trustedrootcert.secureFIlePath) -pfxApiTasksecureFIlePath $(pfxApiTask.secureFIlePath) -pfxPortalTasksecureFIlePath $(pfxPortalTask.secureFIlePath) -pfxManagementTasksecureFIlePath $(pfxManagementTask.secureFIlePath) -azureApplicationId $(azureApplicationId) -azureTenantId $(azureTenantId) -azureClientSecret $(azureClientSecret)'
- stage: integrated_tests
  dependsOn: [appGateway]
  pool:
   vmImage: windows-latest
  jobs:
  - job: do_health_tests
    displayName: perform health test
    steps:
    #- checkout: self
    #  persistCredentials: true
    - task: AzureCLI@2
      enabled: true
      inputs:
        azureSubscription: 'APIM_MicrosoftAzureExternal_multitenant'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Write your PowerShell commands here.
                    
          Write-Host "Hello World"
          Write-Host "install az module"

          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          $azurePassword = ConvertTo-SecureString "$(azureClientSecret)" -AsPlainText -Force
          $psCred = New-Object System.Management.Automation.PSCredential($(azureApplicationId) , $azurePassword)
          Connect-AzAccount -Credential $psCred -TenantId $(azureTenantId)  -ServicePrincipal 
          
          Write-Host After the application gateway deploys, confirm the health status of the API Management back ends in the portal or by running the following command
          
          Get-AzApplicationGatewayBackendHealth -Name $(appGatewayName) -ResourceGroupName $(ResourceGroupNameApim)
    - task: PowerShell@2
      enabled: false
      displayName: Health Check
      env:
        azureClientSecret: $(azureClientSecret)
        azureApplicationId: $(azureApplicationId)
        azureTenantId: $(azureTenantId)
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          $azureClientSecret = Get-ChildItem Env:azureClientSecret
          $azureApplicationId = Get-ChildItem Env:azureApplicationId
          $azureTenantId = Get-ChildItem Env:azureTenantId

          echo $azureApplicationId
          echo $azureTenantId

          Write-Host "Hello World"
          Write-Host "install az module"

          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          $azurePassword = ConvertTo-SecureString "$azureClientSecret" -AsPlainText -Force
          $psCred = New-Object System.Management.Automation.PSCredential($azureApplicationId , $azurePassword)
          Connect-AzAccount -Credential $psCred -TenantId $azureTenantId  -ServicePrincipal
          
          Write-Host After the application gateway deploys, confirm the health status of the API Management back ends in the portal or by running the following command
          
          Get-AzApplicationGatewayBackendHealth -Name $(appGatewayName) -ResourceGroupName $(ResourceGroupNameApim)