<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AddressBook.Service.SOAP</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <ApplicationInsightsResourceId>/subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourceGroups/rg-soap-appservice-linux-007/providers/microsoft.insights/components/appi-soap-api-eck3siixea55c</ApplicationInsightsResourceId>
    <UserSecretsId>fc08ed0e-effa-4093-a162-8f34b45d9372</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="SoapCore" Version="1.1.0.51" />
  </ItemGroup>
</Project>