schema {
  query: QueryObject
  mutation: Mutations
}

scalar Guid

# A movie in the collection
type Movie {
  # Identifier of the movie
  id: Guid
  # Name of the movie
  name: String!
  # Reviews of the movie
  reviews: [Review]
}

# The base mutation for all the entities in our object graph.
type Mutations {
  # Add review to a movie.
  addReview(
    # The unique GUID of the movie.
    id: Guid!
    # Review for the movie
    review: ReviewInput!
  ): Movie
}

type QueryObject {
  movies: [Movie]
  movie(id: Guid!): Movie
}

# A review of the movie
type Review {
  # review Id
  id: Int
  # Guid Id of the movie
  movieId: Guid
  # Name of the reviewer
  reviewer: String!
  # Star rating out of five
  stars: Int!
}

# A review of the movie
input ReviewInput {
  # Name of the reviewer
  reviewer: String!
  # Star rating out of five
  stars: Int!
}
