# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  paths:
    include:
      - src/ApimManagementApiSoln/ApimManagementApi
      #- src/ApimManagementApiSoln/ApimManagementApi

pool:
  vmImage: windows-latest

variables:
  #- group: APIM_apim-automation-end-to-end
  - name: ARTIFACTS_FEED_NAME
    value: APIM_landing_zone_tools

stages:
  - stage: publish_rest_api_tools
    displayName: Publish rest api tools
    jobs:
      - job: publish_rest_api_tools_job
        displayName: Publish rest api utils        
        steps:
          - task: UseDotNet@2
            displayName: Install .NET Core SDK
            inputs:
              version: 6.x
              includePreviewVersions: true
          - task: DotNetCoreCLI@2
            displayName: Publish .NET Core application
            inputs:
              command: publish
              publishWebProjects: false
              projects: '$(Build.SourcesDirectory)/src/ApimManagementApiSoln/ApimManagementApi/ApimManagementApi.csproj'
              arguments: '--output $(Build.ArtifactStagingDirectory) --runtime win-x64 -p:PublishSingleFile=true'
              modifyOutputPath: false
              zipAfterPublish: false
          - task: UniversalPackages@0
            displayName: Publish rest api artifact
            inputs:
              command: publish
              vstsFeedPublish: $(System.TeamProject)/$(ARTIFACTS_FEED_NAME)
              vstsFeedPackagePublish: restapitool
              packagePublishDescription: 'APIM rest apim tool'
